### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by feertuoop** [gadgetmobile/blebox-virtual-devices#2]
Hello, 

after setting up like it's described in the **Usage** section, I've ended up with this result:
![image](https://user-images.githubusercontent.com/77736805/105187758-6e7bd100-5b33-11eb-8a64-c4de0dcb05d3.png)

Docker containters are all exited and manual start doesn't work:
![image](https://user-images.githubusercontent.com/77736805/105188116-d7634900-5b33-11eb-8f11-804c50e066bb.png)

Attaching one of the switchBox container logs:

> Successfully installed rack-2.2.3
Successfully installed tilt-2.0.10
Successfully installed rack-protection-2.1.0
Successfully installed ruby2_keywords-0.0.4
Successfully installed mustermann-1.1.1
Successfully installed sinatra-2.1.0
6 gems installed
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.........
Fetching backports 3.17.0
Installing backports 3.17.0
Using bundler 1.16.1
Fetching multi_json 1.14.1
Installing multi_json 1.14.1
Fetching ruby2_keywords 0.0.2
Installing ruby2_keywords 0.0.2
Using mustermann 1.1.1
Fetching rack 2.2.2
Installing rack 2.2.2
Fetching rack-protection 2.0.8.1
Installing rack-protection 2.0.8.1
Using tilt 2.0.10
Fetching sinatra 2.0.8.1
Installing sinatra 2.0.8.1
Fetching sinatra-contrib 2.0.8.1
Installing sinatra-contrib 2.0.8.1
Bundle complete! 3 Gemfile dependencies, 10 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `/usr/local/bundle`
/usr/local/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate sinatra-contrib-2.0.8.1, because sinatra-2.1.0 conflicts with sinatra (= 2.0.8.1), rack-protection-2.1.0 conflicts with rack-protection (= 2.0.8.1) (Gem::ConflictError)
	from /usr/local/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/src/app/app.rb:4:in `<top (required)>'
	from products/switchBox0.rb:5:in `require_relative'
	from products/switchBox0.rb:5:in `<main>'
Successfully installed sinatra-2.1.0
1 gem installed
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using backports 3.17.0
Using bundler 1.16.1
Using multi_json 1.14.1
Using ruby2_keywords 0.0.2
Using mustermann 1.1.1
Using rack 2.2.2
Using rack-protection 2.0.8.1
Using tilt 2.0.10
Using sinatra 2.0.8.1
Using sinatra-contrib 2.0.8.1
Bundle complete! 3 Gemfile dependencies, 10 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `/usr/local/bundle`
/usr/local/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate sinatra-contrib-2.0.8.1, because sinatra-2.1.0 conflicts with sinatra (= 2.0.8.1), rack-protection-2.1.0 conflicts with rack-protection (= 2.0.8.1) (Gem::ConflictError)
	from /usr/local/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/src/app/app.rb:4:in `<top (required)>'
	from products/switchBox0.rb:5:in `require_relative'
	from products/switchBox0.rb:5:in `<main>'
Successfully installed sinatra-2.1.0
1 gem installed
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using backports 3.17.0
Using bundler 1.16.1
Using multi_json 1.14.1
Using ruby2_keywords 0.0.2
Using mustermann 1.1.1
Using rack 2.2.2
Using rack-protection 2.0.8.1
Using tilt 2.0.10
Using sinatra 2.0.8.1
Using sinatra-contrib 2.0.8.1
Bundle complete! 3 Gemfile dependencies, 10 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `/usr/local/bundle`
/usr/local/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate sinatra-contrib-2.0.8.1, because sinatra-2.1.0 conflicts with sinatra (= 2.0.8.1), rack-protection-2.1.0 conflicts with rack-protection (= 2.0.8.1) (Gem::ConflictError)
	from /usr/local/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/src/app/app.rb:4:in `<top (required)>'
	from products/switchBox0.rb:5:in `require_relative'
	from products/switchBox0.rb:5:in `<main>'

**Comment by gadgetmobile** [comment]
You may have to run `gem update` to update the `Gemfile.lock` and then restart (rebuild?) the docker containers.
